// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trello.api.Repositories.Entities.Context;

namespace trello.api.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20210220152305_Migrations1")]
    partial class Migrations1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.CheckEntityModel", b =>
                {
                    b.Property<int>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskEntityModelTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CheckId");

                    b.HasIndex("TaskEntityModelTaskId");

                    b.ToTable("Check");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.PaintingEntityModel", b =>
                {
                    b.Property<int>("PaintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("PaintingId");

                    b.ToTable("Painting");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.PanelEntityModel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaintingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("PanelId");

                    b.HasIndex("PaintingId");

                    b.ToTable("Panel");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.TaskEntityModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estimated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("PanelId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.TaskUserEntityModel", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskUser");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.UserEntityModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.CheckEntityModel", b =>
                {
                    b.HasOne("trello.api.Repositories.Entities.Models.TaskEntityModel", null)
                        .WithMany("Check")
                        .HasForeignKey("TaskEntityModelTaskId");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.PanelEntityModel", b =>
                {
                    b.HasOne("trello.api.Repositories.Entities.Models.PaintingEntityModel", "Painting")
                        .WithMany("Panel")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.TaskEntityModel", b =>
                {
                    b.HasOne("trello.api.Repositories.Entities.Models.PanelEntityModel", "Panel")
                        .WithMany("Task")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.TaskUserEntityModel", b =>
                {
                    b.HasOne("trello.api.Repositories.Entities.Models.TaskEntityModel", "Task")
                        .WithMany("TaskUser")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trello.api.Repositories.Entities.Models.UserEntityModel", "User")
                        .WithMany("TaskUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.PaintingEntityModel", b =>
                {
                    b.Navigation("Panel");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.PanelEntityModel", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.TaskEntityModel", b =>
                {
                    b.Navigation("Check");

                    b.Navigation("TaskUser");
                });

            modelBuilder.Entity("trello.api.Repositories.Entities.Models.UserEntityModel", b =>
                {
                    b.Navigation("TaskUser");
                });
#pragma warning restore 612, 618
        }
    }
}
